//! **The surgical RON writer** — how an edit reaches `site67.ron` without destroying the file.
//!
//! # Why not `ron::ser::to_string_pretty`
//!
//! `assets/site/site67.ron` is 1401 lines of which **217 are comments** — a 48-line header carrying an
//! ASCII plan of the building and the coordinate contract, a rationale block above every list, and a
//! trailing `// note` on most records. The `props` list is the worst case and the one this editor
//! touches most: 105 comment lines for 86 records, i.e. *more prose than data*. Every one of those
//! lines is somebody's recorded reasoning, and `to_string_pretty` (the pattern used by `settings.rs`
//! and `persist.rs`) would delete all of them on the first save.
//!
//! So this module never re-serialises the document. It holds the file as **text**, remembers which
//! line each editable record came from, and rewrites only the bytes that changed.
//!
//! # Why that is tractable
//!
//! Every record in the file occupies exactly one line, trailing comment included (measured: 1070 of
//! them; the only multi-line forms are the top-level struct and the `door:` block, whose fields are
//! themselves one per line). So "the record at index *i*" is "the line at index `props[i]`", and an
//! edit is a substring replacement inside it.
//!
//! # Field substitution, not record re-emission
//!
//! The file has no single house style — `( piece: Crate,      pos: (41.5, 26.5), yaw:   0.0 ),` and
//! `( piece: FloorButton, pos: ( 11.5,  3.5), yaw:  0.0 ),` are both shipped, with different column
//! widths, because they were authored in separate blocks. Re-emitting a record in *one* canonical
//! style would therefore reformat neighbours' alignment on every save and bury the real change in a
//! noisy diff.
//!
//! [`replace_field`] instead finds one `key: <value>` span and replaces just that, leaving the
//! surrounding whitespace, the sibling fields and the trailing comment exactly as they were. Two
//! consequences worth stating: a no-op save is **byte-identical** to the input (pinned by
//! `tests/site_editor.rs`), and moving one prop changes exactly one line.
//!
//! # One path
//!
//! Every fallible step returns `Err` and stops. There is no "best effort" write, no partial save, and
//! no reformat-the-whole-file recovery: if the scan cannot account for every record the loaded
//! `SiteLayout` contains, [`SourceMap::parse`] fails and the editor refuses to open. A tool that
//! writes level data while unsure which line it is writing is worse than no tool.

use std::path::Path;

use crate::site::layout::{PropPlacement, SiteLayout};

/// The lists this editor owns. The rest of `site67.ron` — `areas`, `floor`, `walls`, `doorways` — is
/// generated by `scripts/gen_site67.py` from its own `ROOMS` table, and editing it here would
/// recreate exactly the drift that script was written to eliminate (read its docstring). Structural
/// editing is a later, deliberate move: port the generator to Rust and delete the Python, so there is
/// still one source of truth.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Section {
    Props,
    Cells,
    Spawns,
}

impl Section {
    /// The RON key that opens this list.
    fn key(self) -> &'static str {
        match self {
            Section::Props => "props",
            Section::Cells => "cells",
            Section::Spawns => "spawns",
        }
    }
}

/// `site67.ron` as lines, plus the line each editable record was parsed from.
///
/// Indices are into [`Self::lines`] and are kept correct across inserts and deletes by
/// [`Self::shift_after`]. They are meaningless against a different file, so a `SourceMap` is only
/// ever valid alongside the `SiteLayout` it was parsed with — which is why [`Self::parse`] takes
/// both and cross-checks the counts.
pub struct SourceMap {
    lines: Vec<String>,
    /// `props[i]` is the line `layout.props[i]` was parsed from.
    props: Vec<usize>,
    cells: Vec<usize>,
    spawns: Vec<usize>,
    /// The `],` line closing each list — where an appended record goes.
    props_end: usize,
    /// Whether the source ended with a newline, so [`Self::render`] can reproduce it exactly.
    trailing_newline: bool,
}

impl SourceMap {
    /// Scan `text` and pair every owned record with its source line.
    ///
    /// `layout` is the already-parsed document; its list lengths are the oracle. A scan that finds a
    /// different number of records than the parser did means this module's assumptions about the
    /// file's shape have been broken (a record wrapped onto two lines, a list renamed), and the only
    /// safe response is to refuse — silently editing the wrong line would corrupt level data in a way
    /// that looks like a successful save.
    pub fn parse(text: &str, layout: &SiteLayout) -> Result<Self, String> {
        let trailing_newline = text.ends_with('\n');
        let lines: Vec<String> = text.lines().map(str::to_owned).collect();

        let (props, props_end) = scan_section(&lines, Section::Props)?;
        let (cells, _) = scan_section(&lines, Section::Cells)?;
        let (spawns, _) = scan_section(&lines, Section::Spawns)?;

        // The cross-check. Each mismatch names the section and both counts, because "which one is
        // wrong" is the first question anyone debugging this will ask.
        for (section, found, want) in [
            (Section::Props, props.len(), layout.props.len()),
            (Section::Cells, cells.len(), layout.cells.len()),
            (Section::Spawns, spawns.len(), layout.spawns.len()),
        ] {
            if found != want {
                return Err(format!(
                    "site editor: scanned {found} `{}` record line(s) but the layout parsed {want}. \
                     A record is probably wrapped across two lines — this writer requires one record \
                     per line (see the module docs).",
                    section.key()
                ));
            }
        }

        Ok(SourceMap {
            lines,
            props,
            cells,
            spawns,
            props_end,
            trailing_newline,
        })
    }

    /// The document as text, byte-identical to the input when nothing has been edited.
    pub fn render(&self) -> String {
        let mut out = self.lines.join("\n");
        if self.trailing_newline {
            out.push('\n');
        }
        out
    }

    /// The source line a prop was parsed from — the unit of undo.
    pub fn prop_line(&self, i: usize) -> Result<&str, String> {
        let at = *self
            .props
            .get(i)
            .ok_or_else(|| format!("site editor: no prop at index {i}"))?;
        self.lines
            .get(at)
            .map(String::as_str)
            .ok_or_else(|| format!("site editor: prop {i} points past the end of the file"))
    }

    /// Overwrite a prop's source line verbatim. The undo path uses this to put back the exact bytes
    /// [`Self::prop_line`] handed out, so a restored record keeps its original formatting and comment
    /// rather than being re-emitted in this module's canonical style.
    pub fn set_prop_line(&mut self, i: usize, line: String) -> Result<(), String> {
        let at = *self
            .props
            .get(i)
            .ok_or_else(|| format!("site editor: no prop at index {i}"))?;
        let slot = self
            .lines
            .get_mut(at)
            .ok_or_else(|| format!("site editor: prop {i} points past the end of the file"))?;
        *slot = line;
        Ok(())
    }

    /// Move a prop. Rewrites the `pos:` field of one line and nothing else.
    pub fn set_prop_pos(&mut self, i: usize, pos: (f32, f32)) -> Result<(), String> {
        let value = format!("({}, {})", fmt_coord(pos.0), fmt_coord(pos.1));
        self.edit_prop_field(i, "pos", &value)
    }

    /// Rotate a prop. Rewrites the `yaw:` field of one line and nothing else.
    ///
    /// Separate from [`Self::set_prop_pos`] deliberately: a rotation must not reformat the position,
    /// so the diff of "I turned this chair" is one field wide.
    pub fn set_prop_yaw(&mut self, i: usize, yaw_deg: f32) -> Result<(), String> {
        let value = fmt_coord(yaw_deg);
        self.edit_prop_field(i, "yaw", &value)
    }

    fn edit_prop_field(&mut self, i: usize, key: &str, value: &str) -> Result<(), String> {
        let at = *self
            .props
            .get(i)
            .ok_or_else(|| format!("site editor: no prop at index {i}"))?;
        let line = self
            .lines
            .get(at)
            .ok_or_else(|| format!("site editor: prop {i} points past the end of the file"))?;
        let edited = replace_field(line, key, value)?;
        self.lines[at] = edited;
        Ok(())
    }

    /// Delete a prop, returning the removed line verbatim so undo can restore it — comment included.
    ///
    /// The caller is expected to surface [`trailing_comment`] to the user before calling this: a
    /// comment is somebody's recorded reasoning and deleting it should be a visible act, not a
    /// side effect.
    pub fn remove_prop(&mut self, i: usize) -> Result<String, String> {
        let at = *self
            .props
            .get(i)
            .ok_or_else(|| format!("site editor: no prop at index {i}"))?;
        if at >= self.lines.len() {
            return Err(format!(
                "site editor: prop {i} points past the end of the file"
            ));
        }
        let removed = self.lines.remove(at);
        self.props.remove(i);
        self.shift_after(at, -1);
        Ok(removed)
    }

    /// Put a previously removed prop back at its old index with its original bytes. The inverse of
    /// [`Self::remove_prop`], and the reason undo restores comments rather than dropping them.
    pub fn restore_prop(&mut self, i: usize, line: String) -> Result<(), String> {
        if i > self.props.len() {
            return Err(format!(
                "site editor: cannot restore prop at index {i}; only {} exist",
                self.props.len()
            ));
        }
        // Land it where the record after it currently starts, or at the list's closing bracket when
        // it was the last one.
        let at = self.props.get(i).copied().unwrap_or(self.props_end);
        self.lines.insert(at, line);
        self.shift_after(at, 1);
        self.props.insert(i, at);
        Ok(())
    }

    /// Append a prop to the end of the `props` list, returning its new index.
    ///
    /// A new record is emitted in the canonical style below rather than copied from a neighbour,
    /// because there is no neighbour to copy when the list is empty and "sometimes match the block
    /// above" is two behaviours wearing one name.
    pub fn insert_prop(&mut self, p: &PropPlacement) -> Result<usize, String> {
        let line = emit_prop(p);
        let at = self.props_end;
        self.lines.insert(at, line);
        self.shift_after(at, 1);
        self.props.push(at);
        Ok(self.props.len() - 1)
    }

    /// Fix up every stored line index after an insertion (`delta = 1`) or deletion (`delta = -1`) at
    /// `at`. Missing one of these lists is how an editor starts writing to the wrong line, so they
    /// are all updated in one place.
    fn shift_after(&mut self, at: usize, delta: isize) {
        let bump = |ix: &mut usize| {
            if *ix >= at {
                *ix = ix.saturating_add_signed(delta);
            }
        };
        self.props.iter_mut().for_each(bump);
        self.cells.iter_mut().for_each(bump);
        self.spawns.iter_mut().for_each(bump);
        if self.props_end >= at {
            self.props_end = self.props_end.saturating_add_signed(delta);
        }
    }
}

/// Find `key: [` and return the line index of every record inside it, plus the index of the `],`
/// that closes it.
///
/// Records are lines whose first non-space character is `(`. Comment lines and blank lines inside the
/// list are skipped and left untouched — preserving them is the whole point of this module.
fn scan_section(lines: &[String], section: Section) -> Result<(Vec<usize>, usize), String> {
    let open = format!("{}: [", section.key());
    let start = lines
        .iter()
        .position(|l| l.trim_start().starts_with(&open))
        .ok_or_else(|| {
            format!(
                "site editor: `{}` list not found in the layout file",
                section.key()
            )
        })?;

    let mut records = Vec::new();
    for (offset, line) in lines.iter().enumerate().skip(start + 1) {
        let t = line.trim_start();
        if t.starts_with("],") || t == "]" {
            return Ok((records, offset));
        }
        if t.starts_with('(') {
            records.push(offset);
        }
    }
    Err(format!(
        "site editor: `{}` list is never closed",
        section.key()
    ))
}

/// Replace the value of `key: <value>` inside one record line, preserving everything else — leading
/// indentation, sibling fields, inter-field padding, and any trailing `// comment`.
///
/// The value runs from just after `key:` to the first `,` or `)` encountered at paren-depth zero, so
/// a tuple value like `(41.5, 26.5)` is matched whole rather than being cut at its inner comma.
/// Padding immediately after the colon is preserved and padding before the terminator is dropped,
/// which keeps a same-width replacement byte-stable.
pub fn replace_field(line: &str, key: &str, value: &str) -> Result<String, String> {
    let needle = format!("{key}:");
    // Search only the code part, so a `//` comment mentioning "yaw:" cannot be mistaken for a field.
    let code_len = comment_split(line);
    let code = &line[..code_len];
    let key_at = code
        .find(&needle)
        .ok_or_else(|| format!("site editor: no `{key}:` field in `{}`", line.trim()))?;

    let after_key = key_at + needle.len();
    // Keep the author's padding between the colon and the value.
    let pad_len = code[after_key..]
        .len()
        .saturating_sub(code[after_key..].trim_start_matches(' ').len());
    let value_start = after_key + pad_len;

    let mut depth = 0usize;
    let mut value_end = None;
    for (ix, ch) in code[value_start..].char_indices() {
        match ch {
            '(' | '[' => depth += 1,
            ')' | ']' if depth > 0 => depth -= 1,
            ')' | ']' if depth == 0 => {
                value_end = Some(value_start + ix);
                break;
            }
            ',' if depth == 0 => {
                value_end = Some(value_start + ix);
                break;
            }
            _ => {}
        }
    }
    let value_end = value_end.ok_or_else(|| {
        format!(
            "site editor: `{key}:` value is not terminated in `{}`",
            line.trim()
        )
    })?;

    // Whitespace between the value and its terminator is the author's column alignment, not part of
    // the value — `yaw:  90.0 ),` must become `yaw:  0.0 ),` and not `yaw:  0.0),`. Trimming it out
    // of the replaced span is what keeps a same-width edit byte-stable.
    let span = &code[value_start..value_end];
    let value_end = value_end - (span.len() - span.trim_end().len());

    let mut out = String::with_capacity(line.len() + value.len());
    out.push_str(&line[..value_start]);
    out.push_str(value);
    out.push_str(&line[value_end..]);
    Ok(out)
}

/// Byte offset where a line's trailing `//` comment begins, or the line's length when it has none.
/// Quote-aware, because `label: "RESEARCH // wing"` is data, not a comment.
fn comment_split(line: &str) -> usize {
    let bytes = line.as_bytes();
    let mut in_quotes = false;
    let mut ix = 0;
    while ix < bytes.len() {
        match bytes[ix] {
            b'\\' if in_quotes => ix += 1,
            b'"' => in_quotes = !in_quotes,
            b'/' if !in_quotes && bytes.get(ix + 1) == Some(&b'/') => return ix,
            _ => {}
        }
        ix += 1;
    }
    line.len()
}

/// The trailing `// comment` on a record line, if it has one. The editor shows this before a delete
/// so that destroying somebody's note is a decision rather than an accident.
pub fn trailing_comment(line: &str) -> Option<&str> {
    let at = comment_split(line);
    (at < line.len()).then(|| line[at..].trim_end())
}

/// Emit a fresh `props` record in the canonical style, matching the shipped file's indentation and
/// spacing. Only used for records that did not exist before — an edit to an existing record goes
/// through [`replace_field`] so its own formatting survives.
fn emit_prop(p: &PropPlacement) -> String {
    let mut out = format!(
        "        ( piece: {:?}, pos: ({}, {}), yaw: {} ",
        p.piece,
        fmt_coord(p.pos.0),
        fmt_coord(p.pos.1),
        fmt_coord(p.yaw)
    );
    if let Some(reason) = &p.waive {
        // RON string escaping, so a reason containing a quote cannot break the file.
        out.push_str(&format!(
            ", waive: Some(\"{}\") ",
            reason.replace('\\', "\\\\").replace('"', "\\\"")
        ));
    }
    out.push_str("),");
    out
}

/// Format a coordinate the way the file does — one decimal place where that is exact, more only when
/// the value genuinely needs it.
///
/// The editor snaps translation to 0.5 m and yaw to 15°, so one decimal is exact for everything it
/// produces and the widened forms are only ever reached by a value that came from somewhere else.
/// Round-tripping through `parse` is what decides, rather than a tolerance, so the written file always
/// reloads to the same `f32` the editor was holding.
fn fmt_coord(v: f32) -> String {
    for places in 1..=6 {
        let s = format!("{v:.places$}");
        if s.parse::<f32>() == Ok(v) {
            return s;
        }
    }
    format!("{v}")
}

/// Write `text` to `path` atomically — tmp file then rename, so a crash mid-write cannot leave a
/// half-written layout on disk. Same shape as `settings::write_settings`.
///
/// The caller is expected to re-load and re-validate afterwards; this function only guarantees the
/// bytes landed.
pub fn save_atomic(path: &Path, text: &str) -> Result<(), String> {
    let parent = path
        .parent()
        .ok_or_else(|| format!("site editor: {} has no parent directory", path.display()))?;
    std::fs::create_dir_all(parent)
        .map_err(|e| format!("site editor: {}: {e}", parent.display()))?;
    let tmp = path.with_extension("ron.tmp");
    std::fs::write(&tmp, text).map_err(|e| format!("site editor: {}: {e}", tmp.display()))?;
    std::fs::rename(&tmp, path).map_err(|e| format!("site editor: {}: {e}", path.display()))?;
    Ok(())
}
