//! **The surgical RON writer, in `site67.ron`'s vocabulary.**
//!
//! The machinery — hold the file as text, remember which line each record came from, rewrite only the
//! bytes that changed — now lives in [`forge_core::ron_surgery`], because the config bake had grown a
//! second implementation of it and the standalone editor needs a third. What is left here is what only
//! this file knows: which lists the editor owns, what a `props` record looks like, and the cross-check
//! against the `SiteLayout` that was parsed alongside it.
//!
//! # Why not `ron::ser::to_string_pretty`
//!
//! `assets/site/site67.ron` is 1401 lines of which **217 are comments** — a 48-line header carrying an
//! ASCII plan of the building and the coordinate contract, a rationale block above every list, and a
//! trailing `// note` on most records. The `props` list is the worst case and the one this editor
//! touches most: 105 comment lines for 86 records, i.e. *more prose than data*. Every one of those
//! lines is somebody's recorded reasoning, and `to_string_pretty` (the pattern used by `settings.rs`
//! and `persist.rs`) would delete all of them on the first save.
//!
//! # Field substitution, not record re-emission
//!
//! The file has no single house style — `( piece: Crate,      pos: (41.5, 26.5), yaw:   0.0 ),` and
//! `( piece: FloorButton, pos: ( 11.5,  3.5), yaw:  0.0 ),` are both shipped, with different column
//! widths, because they were authored in separate blocks. Re-emitting a record in *one* canonical
//! style would therefore reformat neighbours' alignment on every save and bury the real change in a
//! noisy diff.
//!
//! [`forge_core::ron_surgery::replace_field`] instead finds one `key: <value>` span and replaces just
//! that. Two consequences worth stating: a no-op save is **byte-identical** to the input (pinned by
//! `tests/site_editor.rs`), and moving one prop changes exactly one line.
//!
//! # One path
//!
//! Every fallible step returns `Err` and stops. There is no "best effort" write, no partial save, and
//! no reformat-the-whole-file recovery: if the scan cannot account for every record the loaded
//! `SiteLayout` contains, [`SourceMap::parse`] fails and the editor refuses to open. A tool that
//! writes level data while unsure which line it is writing is worse than no tool.

use forge_core::ron_surgery::{fmt_f32, LineDoc};

use crate::site::layout::{PropPlacement, SiteLayout};

/// The record-line helpers this module's callers reach for directly. Re-exported rather than
/// re-implemented — `mod.rs` shows a record's trailing comment before deleting it, `edit.rs` writes
/// the file, and `tests/site_editor.rs` pins the substitution rules.
pub use forge_core::ron_surgery::{replace_field, save_atomic, trailing_comment, Removed};

/// The lists this editor owns. The rest of `site67.ron` — `areas`, `floor`, `walls`, `doorways` — is
/// generated by `scripts/gen_site67.py` from its own `ROOMS` table, and editing it here would
/// recreate exactly the drift that script was written to eliminate (read its docstring). Structural
/// editing is a later, deliberate move: port the generator to Rust and delete the Python, so there is
/// still one source of truth.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Section {
    Props,
    Cells,
    Spawns,
}

impl Section {
    /// The RON key that opens this list.
    fn key(self) -> &'static str {
        match self {
            Section::Props => "props",
            Section::Cells => "cells",
            Section::Spawns => "spawns",
        }
    }
}

/// The list of props, named once so a typo cannot silently address a different list.
const PROPS: &str = "props";

/// `site67.ron` as lines, with every editable record paired to its source line.
///
/// The pairing is meaningless against a different file, so a `SourceMap` is only ever valid alongside
/// the `SiteLayout` it was parsed with — which is why [`Self::parse`] takes both and cross-checks the
/// counts.
pub struct SourceMap {
    doc: LineDoc,
}

impl SourceMap {
    /// Scan `text` and pair every owned record with its source line.
    ///
    /// `layout` is the already-parsed document; its list lengths are the oracle. A scan that finds a
    /// different number of records than the parser did means this module's assumptions about the
    /// file's shape have been broken (a record wrapped onto two lines, a list renamed), and the only
    /// safe response is to refuse — silently editing the wrong line would corrupt level data in a way
    /// that looks like a successful save.
    pub fn parse(text: &str, layout: &SiteLayout) -> Result<Self, String> {
        let keys = [
            Section::Props.key(),
            Section::Cells.key(),
            Section::Spawns.key(),
        ];
        let doc = LineDoc::parse(text, &keys).map_err(|e| format!("site editor: {e}"))?;

        // The cross-check. Each mismatch names the section and both counts, because "which one is
        // wrong" is the first question anyone debugging this will ask.
        for (section, want) in [
            (Section::Props, layout.props.len()),
            (Section::Cells, layout.cells.len()),
            (Section::Spawns, layout.spawns.len()),
        ] {
            let found = doc
                .len(section.key())
                .map_err(|e| format!("site editor: {e}"))?;
            if found != want {
                return Err(format!(
                    "site editor: scanned {found} `{}` record line(s) but the layout parsed {want}. \
                     A record is probably wrapped across two lines — this writer requires one record \
                     per line (see the module docs).",
                    section.key()
                ));
            }
        }

        Ok(SourceMap { doc })
    }

    /// The document as text, byte-identical to the input when nothing has been edited.
    pub fn render(&self) -> String {
        self.doc.render()
    }

    /// The source line a prop was parsed from — the unit of undo.
    pub fn prop_line(&self, i: usize) -> Result<&str, String> {
        self.doc.line(PROPS, i).map_err(prefix)
    }

    /// Overwrite a prop's source line verbatim. The undo path uses this to put back the exact bytes
    /// [`Self::prop_line`] handed out, so a restored record keeps its original formatting and comment
    /// rather than being re-emitted in this module's canonical style.
    pub fn set_prop_line(&mut self, i: usize, line: String) -> Result<(), String> {
        self.doc.set_line(PROPS, i, line).map_err(prefix)
    }

    /// Move a prop. Rewrites the `pos:` field of one line and nothing else.
    pub fn set_prop_pos(&mut self, i: usize, pos: (f32, f32)) -> Result<(), String> {
        let value = format!("({}, {})", fmt_f32(pos.0), fmt_f32(pos.1));
        self.doc.edit_field(PROPS, i, "pos", &value).map_err(prefix)
    }

    /// Rotate a prop. Rewrites the `yaw:` field of one line and nothing else.
    ///
    /// Separate from [`Self::set_prop_pos`] deliberately: a rotation must not reformat the position,
    /// so the diff of "I turned this chair" is one field wide.
    pub fn set_prop_yaw(&mut self, i: usize, yaw_deg: f32) -> Result<(), String> {
        let value = fmt_f32(yaw_deg);
        self.doc.edit_field(PROPS, i, "yaw", &value).map_err(prefix)
    }

    /// Delete a prop, returning the removed record verbatim so undo can restore it — comment
    /// included, and back under the same comment block it was under.
    ///
    /// The caller is expected to surface [`trailing_comment`] to the user before calling this: a
    /// comment is somebody's recorded reasoning and deleting it should be a visible act, not a
    /// side effect.
    pub fn remove_prop(&mut self, i: usize) -> Result<Removed, String> {
        self.doc.remove(PROPS, i).map_err(prefix)
    }

    /// Put a previously removed prop back where it was with its original bytes. The inverse of
    /// [`Self::remove_prop`], and the reason undo restores comments rather than dropping them.
    pub fn restore_prop(&mut self, i: usize, removed: Removed) -> Result<(), String> {
        self.doc.restore(PROPS, i, removed).map_err(prefix)
    }

    /// Append a prop to the end of the `props` list, returning its new index.
    ///
    /// A new record is emitted in the canonical style below rather than copied from a neighbour,
    /// because there is no neighbour to copy when the list is empty and "sometimes match the block
    /// above" is two behaviours wearing one name.
    pub fn insert_prop(&mut self, p: &PropPlacement) -> Result<usize, String> {
        self.doc.append(PROPS, emit_prop(p)).map_err(prefix)
    }
}

/// Keep the editor's errors recognisable as the editor's. The crate underneath speaks about "ron",
/// which is right for a library and unhelpful in a panel that is refusing to save a level.
fn prefix(e: String) -> String {
    format!("site editor: {e}")
}

/// Emit a fresh `props` record in the canonical style, matching the shipped file's indentation and
/// spacing. Only used for records that did not exist before — an edit to an existing record goes
/// through [`replace_field`] so its own formatting survives.
fn emit_prop(p: &PropPlacement) -> String {
    let mut out = format!(
        "        ( piece: {:?}, pos: ({}, {}), yaw: {} ",
        p.piece,
        fmt_f32(p.pos.0),
        fmt_f32(p.pos.1),
        fmt_f32(p.yaw)
    );
    if let Some(reason) = &p.waive {
        // RON string escaping, so a reason containing a quote cannot break the file.
        out.push_str(&format!(
            ", waive: Some(\"{}\") ",
            reason.replace('\\', "\\\\").replace('"', "\\\"")
        ));
    }
    out.push_str("),");
    out
}
