#!/usr/bin/env python3
"""**Write `assets/derived.json` from a staging directory.** The manifest is generated, never typed.

`scripts/fbx_to_glb.py` converts a raw library into a staging directory; this records what came out
so `scripts/derived_assets.py` can verify, cache and restore it without the bytes living in git.

    scripts/manifest_from_staging.py --recipe ozea --staging /tmp/ozea_glb

# The filenames are the index, not `INVENTORY.md`

The converter writes an inventory too, but that file is a **human** aid: it is keyed by basename so
somebody can look up a mesh's authored height, and 411 distinct basenames cover 418 files — the seven
that collide across packs appear once. Reading it as a machine index silently loses those seven. The
staged filename carries its pack as a prefix precisely so the collision is impossible, so the
filename is what this reads.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def normalise(pack: str) -> str:
    """`scripts/fbx_to_glb.py`'s `slug`, restated — it cannot be imported, since that module needs
    `bpy` at import time and only runs inside Blender.

    **Each** non-alphanumeric becomes an underscore and runs are not collapsed, so
    `Pack_SciFi_A_001+_V2.0` becomes `scifi_a_001__v2_0` with two. A collapsing version of this
    matched twenty files short, which is the whole reason it is written out rather than guessed.
    """
    s = pack.lower().replace("pack_", "")
    return "".join(c if c.isalnum() else "_" for c in s).strip("_")


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for block in iter(lambda: f.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


def main() -> int:
    p = argparse.ArgumentParser(prog="manifest_from_staging")
    p.add_argument("--recipe", required=True, help="recipe id, e.g. `ozea`")
    p.add_argument("--staging", required=True, type=Path, help="the converter's --out directory")
    p.add_argument("--source", required=True, help="source path, RELATIVE to the library root")
    p.add_argument("--tool", default="scripts/fbx_to_glb.py")
    p.add_argument("--out-dir", required=True, help="where these land, relative to the repo")
    p.add_argument("--arg", action="append", default=[], help="an argument the tool was run with")
    p.add_argument(
        "--source-root",
        type=Path,
        default=None,
        help="the library root, so pack directory names can be recovered exactly",
    )
    args = p.parse_args()

    files = sorted(args.staging.glob("*.glb"))
    if not files:
        sys.exit(f"no .glb under {args.staging} — did the conversion run?")

    # Recover each output's source pack by matching the filename's prefix against the real directory
    # names, rather than by un-mangling the prefix — the normalisation is lossy (`+` and `.` both
    # become `_`) and guessing backwards through it would be a second, differently-wrong rule.
    packs = {}
    if args.source_root:
        for d in sorted((args.source_root / args.source).iterdir()):
            if d.is_dir():
                packs[normalise(d.name)] = d.name

    outputs, unmatched = [], 0
    for f in files:
        pack = ""
        for norm, real in packs.items():
            if f.name.startswith(norm + "__"):
                pack = real
                break
        if packs and not pack:
            unmatched += 1
        outputs.append(
            {"file": f.name, "pack": pack, "sha256": sha256(f), "bytes": f.stat().st_size}
        )

    manifest_path = REPO / "assets" / "derived.json"
    manifest = (
        json.loads(manifest_path.read_text())
        if manifest_path.exists()
        else {
            "version": 1,
            "note": (
                "DERIVED ASSETS — build output, not source. git keeps this manifest; the bytes live "
                "in a content-addressed cache on the asset library share. See "
                "scripts/derived_assets.py for why and `cargo fvs assets --help` for how. "
                "Generated by scripts/manifest_from_staging.py — do not hand-edit."
            ),
            "recipes": [],
        }
    )
    recipe = {
        "id": args.recipe,
        "source": args.source,
        "tool": args.tool,
        "args": args.arg,
        "out_dir": args.out_dir,
        "outputs": outputs,
    }
    manifest["recipes"] = [r for r in manifest["recipes"] if r["id"] != args.recipe] + [recipe]
    manifest["recipes"].sort(key=lambda r: r["id"])
    manifest_path.write_text(json.dumps(manifest, indent=1) + "\n")

    total = sum(o["bytes"] for o in outputs)
    print(
        f"recipe `{args.recipe}`: {len(outputs)} outputs, {total / 1048576:.0f} MB of bytes, "
        f"described by {manifest_path.stat().st_size / 1024:.0f} KB of manifest"
    )
    if unmatched:
        print(f"  WARNING: {unmatched} output(s) match no pack directory — the prefix rule moved?")
    return 1 if unmatched else 0


if __name__ == "__main__":
    sys.exit(main())
